---

- name: Get list of installed homebrew packages
  command: brew list
  register: homebrew_list
  changed_when: false

- name: Install homebrew packages
  command: "brew install {% if item.source %}{{ item.source }}/{% endif %}{{ item.name }}{% if item.options %} {{item.options}}{% endif %}"
  with_items: homebrew_packages
  when: "'{{ item.name }}' not in homebrew_list.stdout"

- name: Check to see what taps are installed
  command: brew tap
  register: homebrew_tap_list
  changed_when: False

- name: Ensure the right taps are installed for cask
  command: "brew tap {{ item }}"
  with_items: brew_taps
  when: "'{{ item }}' not in homebrew_tap_list.stdout"

- name: Ensure lit of casks
  command: "brew cask list"
  register: cask_list
  changed_when: false

- name: Install cask packages
  command: "brew cask install --appdir={{cask_appdir}} {{ item.name }}"
  with_items: cask_packages
  when: "'{{ item.name }}' not in cask_list.stdout"

- name: Install fonts
  command: "brew cask install --appdir={{cask_appdir}} {{ item }}"
  with_items: cask_fonts
  when: "'{{ item }}' not in cask_list.stdout"